workspace:
  base: /cpp

pipeline:
  build:
    image: madduci/docker-ubuntu-cpp
    commands:
      - apt-get -qq -yy update
      - apt-get -qq -yy -o=Dpkg::Use-Pty=0 install libcurl4-openssl-dev cmake git
      - mkdir ./build && cd ./build && cmake .. && make

  test:
    image: madduci/docker-ubuntu-cpp
    commands:
      - apt-get -qq -yy update
      - apt-get -qq -yy -o=Dpkg::Use-Pty=0 install libcurl4-openssl-dev git
      - cd ./build && make check
