language: cpp
compiler:
  - clang
  - gcc

install:
  - sudo apt-get install cmake
  - mkdir ./build
  - cd ./build && cmake ..
  - make
  - sudo make install

script:
  - make test

after_script:
  - sudo make uninstall
