language: generic

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - valgrind

jobs:
  include:
    - stage: test
      os: linux
      cache:
        apt: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - CXX=g++-4.9
        - CC=gcc-4.9

    - stage: test
      os: linux
      cache:
        apt: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - CXX=g++-5
        - CC=gcc-5

    - stage: test
      os: linux
      cache:
        apt: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CXX=g++-6
        - CC=gcc-6

    - stage: test
      os: linux
      cache:
        apt: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CXX=g++-7
        - CC=gcc-7

    - stage: test
      os: linux
      cache:
        apt: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
          packages:
            - clang-3.5
            - libc++-dev
      env:
        - CXX=clang++-3.5
        - CC=clang-3.5

    - stage: test
      os: linux
      cache:
        apt: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libc++-dev
      env:
        - CXX=clang++-3.6
        - CC=clang-3.6

    - stage: test
      os: linux
      cache:
        apt: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libc++-dev
      env:
        - CXX=clang++-3.7
        - CC=clang-3.7

    - stage: test
      os: linux
      cache:
        apt: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - libc++-dev
      env:
        - CXX=clang++-3.8
        - CC=clang-3.8

    - stage: test
      os: linux
      cache:
        apt: true
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - libc++-dev
      env:
        - CXX=clang++-3.9
        - CC=clang-3.9

    - stage: test
      os: linux
      cache:
        apt: true
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libc++-dev
      env:
        - CXX=clang++-4.0
        - CC=clang-4.0

    - stage: test
      os: linux
      cache:
        apt: true
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libc++-dev
      env:
        - CXX=clang++-5.0
        - CC=clang-5.0

    - stage: doc
      os: linux
      cache:
        apt: true
      addons:
        apt:
          packages:
            - doxygen
      script:
        - mkdir ./build
        - cd ./build && cmake ..
        - make doc

    - stage: install
      os: linux
      cache:
        apt: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - CXX=g++-4.9
        - CC=gcc-4.9
      script:
        - mkdir ./build
        - cd ./build && cmake ..
        - make
        - sudo make install
        - sudo make uninstall

script:
  - mkdir ./build
  - cd ./build && cmake ..
  - make
  - make check
